---
title: "Read loom from FlyCellAtlas and analyze"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Read loom from FlyCellAtlas and analyze}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
#devtools::install_github("ipatop/FlyCellAtlas.download.with.annotations")
library(FlyCellAtlas.download.with.annotations)
```

## General

This package is designed to analyze the data from the [FlyCellAtlas](https://flycellatlas.org)

## Dependencies

This packages depends on the following packages, they should be loaded automatically but just in case if you want you can load them manually

```
library("assertthat")
library("Seurat")
library("SeuratDisk")
library("grDevices")
library("ggplot2")
library("hdf5r")
library("loomR")
library("scater")
library("patchwork")
library("SeuratObject")
library("dplyr")
library("tidyr")
library("cowplot")
```
## Run example data

``` r
#Files are in https://flycellatlas.org
# Here we download the body wall 10X loom and h5ad
download.file(url = "https://cloud.flycellatlas.org/index.php/s/egxzns8NgtCjonB/download",destfile = "./bodywall.loom")
download.file(url = "https://cloud.flycellatlas.org/index.php/s/sZZMSbcNk4SWtHE/download",destfile = "./bodywall.h5ad")

loom_file<-"./bodywall.loom"
h5ad_file<-"./bodywall.h5ad"
## basic example code to create a new Seurat object with annotations from FlyCellAtlas
bodywall_new<-loom_too_Seurat_brandNew(loom_file =loom_file,h5ad_file=h5ad_file)
```

Now `bodywall_new` is a Seurat object we can not plot etc

``` r

DimPlot(bodywall_new,repel = T,label = T,reduction = "umap", group.by = "annotation")+ NoLegend()

```
